FROM `r liftr_from`

MAINTAINER `r liftr_maintainer` <`r liftr_maintainer_email`>

RUN  rm -f /var/lib/dpkg/available \
  && rm -rf  /var/cache/apt/* \
  && apt-get update \
  && apt-get install  -y --no-install-recommends \
    ca-certificates \
    libssl-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libssh2-1-dev \
    git

`r liftr_syslib`

`r liftr_texlive`

`r liftr_pandoc`

RUN Rscript -e "install.packages(c(`r liftr_factorypkg`), repos = 'https://cran.rstudio.com')"

`r liftr_cranpkg`
`r liftr_biocpkg`
`r liftr_ghpkg`

```{r echo= FALSE,  results = "asis"}
if(length(liftr_extra))
  writeLines(liftr_extra)
```

RUN mkdir /liftrroot/
WORKDIR /liftrroot/
