FROM `r liftr_from`

MAINTAINER `r liftr_maintainer` <`r liftr_maintainer_email`>

# System dependencies for required R packages
RUN  rm -f /var/lib/dpkg/available \
  && rm -rf  /var/cache/apt/* \
  && apt-get update -qq \
  && apt-get install -t unstable -y --no-install-recommends \
    ca-certificates \
    libssl-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libssh2-1-dev \
    git

`r liftr_syslib`

`r liftr_texlive`

`r liftr_pandoc`

RUN Rscript -e "install.packages(c(`r liftr_cranpkg`), repos = 'http://cran.rstudio.com')"
`r liftr_biocpkg`
`r liftr_ghpkg`

RUN mkdir /liftrroot/
WORKDIR /liftrroot/
