FROM `r liftr_from`

MAINTAINER `r liftr_maintainer` <`r liftr_maintainer_email`>

# System dependencies for required R packages
RUN  rm -f /var/lib/dpkg/available \
  && rm -rf  /var/cache/apt/* \
  && apt-get update -qq \
  && apt-get install -t unstable -y --no-install-recommends \
    ca-certificates \
    libssl-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libssh2-1-dev \
    git

`r liftr_syslib`

`r liftr_texlive`

# Pre-compiled pandoc required by rmarkdown from cardcorp/r-pandoc
RUN mkdir -p /opt/pandoc \
  && wget --no-check-certificate -O /tmp/pandoc.zip https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.13.1.zip \
  && unzip -j /tmp/pandoc.zip "pandoc-1.13.1/linux/debian/x86_64/pandoc" -d /opt/pandoc \
  && chmod +x /opt/pandoc/pandoc \
  && ln -s /opt/pandoc/pandoc /usr/local/bin \
  && unzip -j /tmp/pandoc.zip "pandoc-1.13.1/linux/debian/x86_64/pandoc-citeproc" -d /opt/pandoc \
  && chmod +x "/opt/pandoc/pandoc-citeproc" \
  && ln -s "/opt/pandoc/pandoc-citeproc" /usr/local/bin \
  && rm -f /tmp/pandoc.zip

RUN Rscript -e "install.packages(c(`r liftr_cranpkg`), repos = 'http://cran.rstudio.com')"
`r liftr_biocpkg`
`r liftr_ghpkg`

RUN mkdir /liftrroot/
WORKDIR /liftrroot/
